module.exports = {
    GLOBAL_CHAT: "GLOBAL_CHAT",
    USER_CONNECTED: "USER_CONNECTED",
    MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
    MESSAGE_SENT: "MESSAGE_SENT",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    USER_CHANGE: "USER_CHANGE",
    VERIFY_USER: "VERIFY_USER",
    LOGOUT: "LOGOUT",
    LINEDRAWN: "LINEDRAWN",
    SCREENCLEAR: "SCREENCLEAR",
    LOG: "LOG"
}